[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hidden_hand = "9hmucQcDZ1SJDCD8oM7KV5Rngfx7ZAcwZWk3WTghVDTg"

[programs.devnet]
hidden_hand = "9hmucQcDZ1SJDCD8oM7KV5Rngfx7ZAcwZWk3WTghVDTg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../.keys/house-keypair.json"

[scripts]
test = "echo 'no tests'"
